### ISSUE TITLE
[Bug]: Failed to run `config` for nvim-scissors, attempt to index a boolean value.

### ISSUE THREAD

**Issue by sweetbbak** [chrisgrieser/nvim-scissors#15]
### Bug Description

Failed to run `config` for nvim-scissors                                                      
                                                                                              
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:373: attempt to index a boolean va
lue          

### To Reproduce

Update to latest version and start neovim.
Using LazyVim package manager and here's the base config:
```lua
return {
    "chrisgrieser/nvim-scissors",
    dependencies = "nvim-telescope/telescope.nvim", -- optional
    opts = {
        snippetDir = "/home/me/.snippets",
    },

    -- require("luasnip.loaders.from_vscode").lazy_load({ paths = { "/home/me/.snippets" } }),
    require("luasnip.loaders.from_vscode").lazy_load(),

    -- When used in visual mode prefills the selection as body.
    vim.keymap.set("n", "<leader>si", function()
        require("scissors").editSnippet()
    end),
    vim.keymap.set({ "n", "x" }, "<leader>sa", function()
        require("scissors").addNewSnippet()
    end),
}

```

### neovim version

```Text
v0.9.5
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the plugin's FAQ](https://github.com/chrisgrieser/nvim-scissors#cookbook--faq).

**Comment by chrisgrieser** [comment]
Not sure what exactly the issue is, but I already see 4 issues on your side:
1. You use nvim 0.9.5, while the minimum required version for scissors is 0.10, as stated in the readme as well as the commit log and the plugin-internal notifications.
2. Your config is missing either a `setup` call or lazy.nvim's `opts` spec specifying the `snippetDir`, as stated in the readme as well.
3. `require("luasnip.loaders.from_vscode").lazy_load()` is missing an argument. (And it also needs to be done in the Luasnip config to begin with.)
4. `require("luasnip.loaders.from_vscode").lazy_load()` and the keymaps are not enclosed in the Lazy `config` key, and therefore likely causing some problems as that makes them invalid I assume. Refer to the Lazyvim readme for correct plugin setup with Lazyvim.

Since everything works on my end, I assume one of these issues is causing the problem.

I'd recommend trying to setup expansion of custom snippets with only Luasnip or nvim-snippets first. If you have that successfully working, then add nvim-scissors as additional plugin to create/edit those snippets more conveniently. That way, it's easier to figure out where your issue lies, since currently, I assume your snippet setup will not work whether you use nvim-scissors or not.

**Comment by sweetbbak** [comment]
The setup I provided does call opts with the path to a snippet dir, but regardless, this is what is specified in the README, and it also fails with the same error:
```lua
return {
	"chrisgrieser/nvim-scissors",
	dependencies = { "nvim-telescope/telescope.nvim", "L3MON4D3/LuaSnip" }, 
	opts = {
		snippetDir = "~/.snippets",
	} 
},
```

its the same error with using the call to setup:
```lua
return {
    "chrisgrieser/nvim-scissors",
    dependencies = "nvim-telescope/telescope.nvim", -- optional
    
    -- fails with and without this commented out:
    -- opts = {
    --     snippetDir = "/home/me/.snippets",
    -- },

    config = function()
        -- default settings
        require("scissors").setup({
            snippetDir = vim.fn.stdpath("config") .. "/snippets",
            editSnippetPopup = {
                height = 0.4, -- relative to the window, number between 0 and 1
                width = 0.6,
                border = "rounded",
                keymaps = {
                    cancel = "q",
                    saveChanges = "<CR>", -- alternatively, can also use `:w`
                    goBackToSearch = "<BS>",
                    deleteSnippet = "<C-BS>",
                    duplicateSnippet = "<C-d>",
                    openInFile = "<C-o>",
                    insertNextToken = "<C-t>", -- insert & normal mode
                    jumpBetweenBodyAndPrefix = "<C-Tab>", -- insert & normal mode
                },
            },
            telescope = {
                -- By default, the query only searches snippet prefixes. Set this to
                -- `true` to also search the body of the snippets.
                alsoSearchSnippetBody = false,
            },
            -- `none` writes as a minified json file using `vim.encode.json`.
            -- `yq`/`jq` ensure formatted & sorted json files, which is relevant when
            -- you version control your snippets.
            jsonFormatter = "none", -- "yq"|"jq"|"none"
        })
    end,
}

```

I should have been more clear that in my original config, I was trying to troubleshoot by trying out both of these lines which are recommended in the faq, my original config did have that path that you mentioned prior to it breaking today:
```lua
require("luasnip.loaders.from_vscode").lazy_load({ paths = { "/home/me/.snippets" } }),
-- require("luasnip.loaders.from_vscode").lazy_load(),
```
I've also tried with and without the keybindings for each of these configurations.

I can avoid the error by doing this
```lua
    "chrisgrieser/nvim-scissors",
    dependencies = { "nvim-telescope/telescope.nvim", "L3MON4D3/LuaSnip" },
    opts = {
        snippetDir = "/home/me/.snippets",
    },

    config = function() end,
```
but then it fails when I call scissors via lua
```lua
:lua require("scissors").editSnippet()
-- with error
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
stack traceback:
	[string ":lua"]:1: in main chunk

```

**Comment by chrisgrieser** [comment]
My bad, 2. was wrong, nonetheless you are not on nvim 0.10 which is required

**Comment by sweetbbak** [comment]
Okay, thanks for your time.

**Comment by chrisgrieser** [comment]
If you update to nvim 0.10 and the issue still occurs, I'd ask in the lazyvim Github discussions. 

In the errors messages you posted, it was never nvim-scissors throwing the error or even appearing in the stacktrace. So the cause of the error has to be some issue with lazyvim.

**Comment by Drew-Daniels** [comment]
I'm actually getting a similar error as @sweetbbak and I'm running `nvim 0.10.2` (installed with `homebrew`):

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/f116e59c-5e49-4257-a701-33385b99699e">

This error message appears whenever I try creating or editing an existing snippet.

```sh
❯ nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

I have configured `nvim-scissors` with `lazy.nvim` like:

```lua
return require("lazy").setup({
  {
    "chrisgrieser/nvim-scissors",
    dependencies = { "nvim-telescope/telescope.nvim", "garymjr/nvim-snippets" },
  },
})

```

I am then calling `.setup()` like this:

```lua
require("scissors").setup({
  snippetDir = vim.fn.stdpath("config") .. "/snippets",
  jsonFormatter = "jq",
})
```

`nvim/snippets/package.json`:

```json
{
  "name": "my-snippets",
  "contributes": {
    "snippets": [
      {
        "language": "lua",
        "path": "./lua.json"
      },
    ]
  }
}
```

`nvim/snippets/lua.json`
```json
{
  "TODO": {
    "body": "-- TODO: ${1:TODO}",
    "prefix": "td"
  }
}
```

My snippets are getting updated and saved however, so it looks like this might be an issue with `nvim-snippets`

**Comment by chrisgrieser** [comment]
@Drew-Daniels From what I can tell, this looks like a different error message to me.

And indeed, the error message indicates that it's an issue with `nvim-snippets` as opposed to `nvim-scissors`. Effectively, nvim-scissors only calls the reloading function like this:
```lua
local path = "path/to/a/json/file/in/your/snippet-dir/lang.json"
require("snippets.utils").reload_file(path)
```

This normally gives you a confirmation message like "x snippets reloaded", and I assume this fails on your end because of some issue with `nvim-snippets` which is unfortunately out of my control. 

I suggest opening an issue at nvim-snippets. If there is nonetheless still some issue with nvim-scissors, please open a new bug report.

**Comment by Drew-Daniels** [comment]
@chrisgrieser thanks for the confirmation. Created an issue here to track this issue in `nvim-snippets`:

https://github.com/garymjr/nvim-snippets/issues/63
