### ISSUE TITLE
[Bug]: a new filetype.json should not be created when cancel it.

### ISSUE THREAD

**Issue by rogtino** [chrisgrieser/nvim-scissors#22]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the docs, and in particular the FAQ](https://github.com/chrisgrieser/nvim-scissors#table-of-contents).
- [X] The problem is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as Luasnip or nvim-snippets.)

### Bug Description

a new json will be created when I cancel creating snippet,this should be avoided because a new file with empty content is useless.
Also, an option to remove the json file automatically when the file contains no snippet would be helpful.

### To Reproduce

go to a new filetype ,create a snippet and cancel, an empty json file will be created.

### neovim version

```Text
NVIM v0.11.0-dev-1043+ge4a74e986
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

**Comment by chrisgrieser** [comment]
Technically, this is not a bug, since bootstrapping a new snippet file if there is currently none is the intended behavior.

I am not entirely sure whether the—in my view very rare—edge case of "created new snippet for filetype that has no snippet yet, but changed my mind midway" justifies adding an extra option to disable automatic bootstrapping. 

In the very rare case this happens, no harm is done, and you are still able to manually delete the file (and its reference in the package.json) with little work.
