### ISSUE TITLE
[Bug]: Attempting to delete prefix moves snippet lines up to prefix

### ISSUE THREAD

**Issue by zolrath** [chrisgrieser/nvim-scissors#6]
### Bug Description

When deleting a prefix with `dd`, the prefix line is deleted but the prefix count is not changed.
The first line of the snippet instead moves up to the prefix section.

### Relevant Screenshot

Before deleting a prefix:
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/5311b305-f68b-4b12-aad9-7863d79cf635)

After deleting a prefix:
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/05ff2224-a24c-4124-b250-d0a5c24e1f96)

### To Reproduce

Create a snippet with multiple prefixes and delete one of the prefixes with `dd`

### neovim version

```Text
NVIM v0.9.5
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the plugin's FAQ](https://github.com/chrisgrieser/nvim-scissors#cookbook--faq).

**Comment by chrisgrieser** [comment]
Hmm, it seems that this is an unintended side effect of the changed behavior of the divider line through 111e703. Looks like a trade-off, where you have to choose between the unintuitive behavior from #4 or the issue here. Not sure whether this is the intended behavior `extmarks`, or potentially a bug with nvim core.

For what it's worth, I added a workaround that fixes this issue without re-introducing the behavior from #4.
